data:
  tickers:
    - "^GSPC"    # S&P500 index symbol
  start_date: "2018-01-01"
  end_date: "2023-01-01"

model:
  epochs: 50
  batch_size: 32
  lstm_units: 50
  dropout: 0.2

# Momentum strategy parameters
momentum_window: 12
momentum_threshold: 0.01

# Mean Reversion strategy parameters
mean_reversion_window: 20
mean_reversion_threshold: 1.5

# Moving Average strategy parameters
fast_ma_window: 20
slow_ma_window: 50

# MACD strategy parameters
macd_fast_period: 12
macd_slow_period: 26
macd_signal_period: 9

# ML Strategy Parameters
ml_threshold: 0.0
window_size: 60

# Ensemble strategy weights (optional, default is equal weighting)
ensemble_weights:
  Momentum: 0.2
  MeanReversion: 0.2
  MovingAverageCrossover: 0.2
  MACD: 0.2
  ML: 0.2

strategy:
  threshold: 0.0
  stop_loss: 0.05
  take_profit: 0.1
  rebalance_frequency: "1M"  # Monthly rebalancing
  transaction_cost: 0.001    # 0.1% transaction cost
  slippage: 0.001            # 0.1% slippage
  risk_free_rate: 0.02       # Annual risk-free rate for Sharpe ratio calculation 
  risk_aversion: 0.5         # Risk aversion coefficient for Kelly criterion
  max_drawdown: 0.2          # Maximum drawdown limit for risk management
  max_position_size: 0.2     # Maximum position size for each asset
  min_position_size: 0.05    # Minimum position size for each asset
  min_sharpe_ratio: 1.0      # Minimum Sharpe ratio for strategy to be considered
  min_sortino_ratio: 1.0     # Minimum Sortino ratio for strategy to be considered
  min_calmar_ratio: 1.0      # Minimum Calmar ratio for strategy to be considered